name: Automatic build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: gradle:latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Assemble
        run: |
          mkdir -p $HOME/libs/android/sdk/licenses
          export ANDROID_SDK_ROOT=$HOME/libs/android/sdk
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
          gradle assemble
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automatic Build"
          files: app/build/outputs/apk/release/app-release-unsigned.apk.apk
